title: JYKIM BLOG
description: developer with awesome blog!

url: https://j-yong99.github.io/
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: j-yong99
  email: alexj99@kookmin.ac.kr


google_analytics: "G-MZB8ZZY7DN"

disqus:
    comments: true
    shortname: j-yong99.github.io


  

